name: Deploy

on:
  push:
    tags:  # 当有新的 tag 时触发
      - '*'  # 匹配所有 tag

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Build Zip
        run: yarn zip
      - name: Build CRX
        run: yarn crx
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

